
###
# 查询所有校园宣讲会信息
GET http://localhost:8201/api/campus/query_g?skip=0&limit=10 HTTP/1.1
// GET http://oa.chinahuian.cn/jobs/campus/query?skip=0&limit=10 HTTP/1.1
Accept: application/json

###
# 查询指定用户校园宣讲会信息
#GET http://localhost:7001/api/campus/list?corp.id=5bd233253931128db02d9849&skip=0&limit=10 HTTP/1.1
GET http://oa.chinahuian.cn/jobs/campus/list?corp.id=5a9e2ed7a44cd66c81cfcf61&skip=0&limit=10 HTTP/1.1
Accept: application/json

###
# 简要信息列表
#GET http://localhost:7001/api/campus/simple?corp.id=5bd233253931128db02d9849&skip=0&limit=10 HTTP/1.1
GET http://oa.chinahuian.cn/jobs/campus/simple?corp.id=5a9e2ed7a44cd66c81cfcf61&skip=0&limit=10 HTTP/1.1
Accept: application/json

###
# 创建（申请发布）校园宣讲会信息
POST http://localhost:8201/api/campus/create?corp.id=5bd233253931128db02d9849 HTTP/1.1
#POST http://oa.chinahuian.cn/jobs/campus/create?corp.id=5a9e2ed7a44cd66c81cfcf61 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "subject": "福瑞科技2018年校园校园招聘(二)",
  "content": "<p>福瑞科技2018年校园校园招聘</p>",
  "city": {
    "code": "220100",
    "name": "吉林省长春市"
  },
  "address": "南岭校区",
  "school": "吉林大学",
  "time": "2018年3月20日",
  "unit": "99991",
  "date": "2018-10-29",
  "contact": "杨帆",
  "email": "free1977@163.com",
  "jobs": [{
    "name": "Java程序员",
    "count": 5,
    "requirement": "计算机软件,软件工程,信息技术"
  },{
    "name": "界面设计",
    "count": 2,
    "requirement": "美术,艺术设计"
  },{
    "name": "前端程序员",
    "count": 10,
    "requirement": "计算机软件,信息技术"
  }]
}

###
# 修改校园宣讲会信息
#POST http://localhost:7001/api/campus/update?corp.id=5bd233253931128db02d9849&_id=5aacbdad96910747e4f37433 HTTP/1.1
POST http://oa.chinahuian.cn/jobs/campus/update?corp.id=5a9e2ed7a44cd66c81cfcf61&_id=5aacc3632708584ca51f3fd3 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "content": "<p>福瑞科技2018年校园招聘吉林站...</p>"
}

###
# 获取校园宣讲会信息
GET http://localhost:8201/api/campus/fetch?_id=5aacbdad96910747e4f37433 HTTP/1.1
#GET http://oa.chinahuian.cn/jobs/campus/fetch?_id=5aacc3632708584ca51f3fd3 HTTP/1.1
Accept: application/json


